language: c++
sudo: false
matrix:
  include:
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-precise
          packages:
            - clang-3.4
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test