language: c++
sudo: false
matrix:
  include:
    - os: linux
      compiler: clang
      env: CONAN_ARGS='-s arch=x86_64 -s build_type=Release -s compiler=clang -s compiler.libcxx=libstdc++ -s compiler.version=3.4 --buil'
      addons:
        apt:
          sources:
            - llvm-toolchain-precise
          packages:
            - clang-3.4
    - os: linux
      compiler: gcc
      env: CONAN_ARGS='-s arch=x86_64 -s build_type=Release -s compiler=g++ -s compiler.libcxx=libstdc++ -s compiler.version=3.4 --buil'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9

before_script:
  - pip install conan

script:
  - mkdir build
  - cd build
  - conan install -f ../conanfile.txt ${CONAN_ARGS}
  - cmake -DUSE_CONAN_LIBS=true ..
  - make
  - make test