language: c++
sudo: true
matrix:
  include:
    - os: linux
      compiler: clang
      env: CONAN_ARGS='-s arch=x86_64 -s build_type=Release -s compiler=clang -s compiler.libcxx=libstdc++ -s compiler.version=3.4 --build' CXX=clang++-3.4 CC=clang-3.4
      addons:
        apt:
          sources:
            - llvm-toolchain-precise-3.4
          packages:
            - clang-3.4
    - os: linux
      compiler: gcc
      env: CONAN_ARGS='-s arch=x86_64 -s build_type=Release -s compiler=gcc -s compiler.libcxx=libstdc++ -s compiler.version=4.9 --build' CXX=g++-4.9 CC=gcc-4.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9

before_script:
  - sudo pip install conan
  
install:
- "[ $CXX = g++ ] && export CXX=g++-4.9 || true"
- "[ $CXX = clang++ ] && export CXX=clang-3.4 || true"

script:
  - mkdir build
  - cd build
  - conan install -f ../conanfile.txt ${CONAN_ARGS}
  - cmake -DUSE_CONAN_LIBS=true ..
  - make
  - make test
