version: '{build}'

os: Visual Studio 2015

environment:
  matrix:
    - compiler: msvc-14-seh
      generator: "Visual Studio 14 2015"
      conan_args: "-s arch=x86 -s build_type=Release -s compiler='Visual Studio' -s compiler.version=14 --build"

    - compiler: msvc-14-seh
      generator: "Visual Studio 14 2015 Win64"
      conan_args: "-s arch=x86_64 -s build_type=Release -s compiler='Visual Studio' -s compiler.version=14 --build"

configuration:
  - Debug

build:
  verbosity: minimal

install:
- ps: |
    Write-Output "Compiler: $env:compiler"
    Write-Output "Generator: $env:generator"
- cmd: echo "Downloading conan..."
- cmd: set PATH=%PATH%;%PYTHON%/Scripts/
- cmd: pip.exe install conan
- cmd: conan user # Create the conan data directory
- cmd: conan --version

build_script:
- ps: |
    md build -Force | Out-Null
    cd build

    & conan install -f ../conanfile.txt $en:conan_args
    $conf = "-DCMAKE_CONFIGURATION_TYPES=Debug;Release -DUSE_CONAN_LIBS=true -DCMAKE_VERBOSE_MAKEFILE=true"
    & cmake -G "$env:generator" $conf ..
    if ($LastExitCode -ne 0) {
        throw "Exec: $ErrorMessage"
    }
    & make
    if ($LastExitCode -ne 0) {
        throw "Exec: $ErrorMessage"
    }

test_script:
- ps: |
    & make test
    if ($LastExitCode -ne 0) {
        throw "Exec: $ErrorMessage"
    }
