version: '{build}'

os: Visual Studio 2015

environment:
  matrix:
    - compiler: msvc-14-seh
      generator: "Visual Studio 14 2015"
      conan_args: "-s arch=x86 -s build_type=Release -s compiler=\"Visual Studio\" -s compiler.version=14 --build"

    - compiler: msvc-14-seh
      generator: "Visual Studio 14 2015 Win64"
      conan_args: "-s arch=x86_64 -s build_type=Release -s compiler=\"Visual Studio\" -s compiler.version=14 --build"

configuration:
  - Debug

build:
  verbosity: detailed

install:
- cmd: echo Downloading conan...
- cmd: set PATH=%PATH%;%PYTHON%/Scripts/
- cmd: pip.exe install conan
- cmd: conan user # Create the conan data directory
- cmd: conan --version

build_script:
- cmd: mkdir build
- cmd: cd build
- cmd: echo conan install -f ../conanfile.txt %conan_args%
- cmd: conan install -f ../conanfile.txt %conan_args%
- cmd: echo cmake -G "%generator%" -DUSE_CONAN_LIBS=true -DCMAKE_VERBOSE_MAKEFILE=true ..
- cmd: cmake -G "%generator%" -DUSE_CONAN_LIBS=true -DCMAKE_VERBOSE_MAKEFILE=true ..
- cmd: echo msbuild hackerrank.sln
- cmd: msbuild hackerrank.sln

test_script:
- cmd: set PATH=%PATH%;%CD%\bin
- cmd: ctest -j -V
