version: '{build}'

os: Visual Studio 2015

environment:
  matrix:
    - compiler: msvc-14-seh
      generator: "Visual Studio 14 2015"
      conan_args: "-s arch=x86 -s build_type=Release -s compiler=\"Visual Studio\" -s compiler.version=14 --build"

    - compiler: msvc-14-seh
      generator: "Visual Studio 14 2015 Win64"
      conan_args: "-s arch=x86_64 -s build_type=Release -s compiler=\"Visual Studio\" -s compiler.version=14 --build"

configuration:
  - Debug

build:
  verbosity: detailed

install:
  - cmd: |
         echo Downloading conan...
         set PATH=%PATH%;%PYTHON%/Scripts/
         pip.exe install conan
         conan user
         conan --version

build_script:
  - cmd: |
         mkdir build
         cd build
         echo conan install ../conanfile.txt %conan_args%
         conan install ../conanfile.txt %conan_args%
         echo cmake -G "%generator%" -DUSE_CONAN_LIBS=true -DCMAKE_VERBOSE_MAKEFILE=true ..
         cmake -G "%generator%" -DUSE_CONAN_LIBS=true -DCMAKE_VERBOSE_MAKEFILE=true ..
         echo msbuild /m hackerrank.sln
         msbuild /m hackerrank.sln

test_script:
  - cmd: |
         set PATH=%PATH%;%CD%\bin
         ctest -j -V
